name: Sync with Notepad++ Releases

# on:
#   schedule:
#     - cron: '0 0 * * *'  # Runs once every day
on:
  push:
    paths:
      - '.github/workflows/blank.yml'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Check Notepad++ releases
        run: |
          current_version=$(curl -s https://api.github.com/repos/notepad-plus-plus/notepad-plus-plus/releases/latest | jq -r '.tag_name' | sed 's/v//')
          if [[ -z "$(git tag -l $current_version)" ]]; then
            echo "Creating release for version $current_version"
            wget -O npp.zip "https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v$current_version/npp.$current_version.portable.x64.zip"
            git tag $current_version
            git push --tags
            echo "::set-output name=release_tag::$current_version"
          else
            echo "No new releases found"
          fi

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.sync.outputs.release_tag }}
          release_name: Release ${{ steps.sync.outputs.release_tag }}
          body: |
            New release: ${{ steps.sync.outputs.release_tag }}
          draft: false
          prerelease: false

      - name: Commit and push changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          git add .
          git commit -m "Updated release to version ${{ steps.sync.outputs.release_tag }}"
          git push
