name: Sync with Notepad++ Releases

# on:
#   schedule:
#     - cron: '0 0 * * *'  # Runs once every day
on:
  push:
    paths:
      - '.github/workflows/blank.yml'


jobs:
  copy-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ecs_notepad-plus-plus
        uses: actions/checkout@v2
        with:
          repository: 'zachariah-george/ecs_npp'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest Notepad++ release
        id: get-release
        run: |
          wget -qO- https://api.github.com/repos/notepad-plus-plus/notepad-plus-plus/releases/latest \
          | grep "tag_name" \
          | cut -d : -f2,3 \
          | tr -d \" \
          | tr -d , \
          | tr -d ' ' > version.txt
          echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Download Notepad++ portable
        run: |
          wget https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/${{ env.VERSION }}/npp.${{ env.VERSION }}.portable.x64.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./npp.${{ env.VERSION }}.portable.x64.zip
          asset_name: npp.${{ env.VERSION }}.portable.x64.zip
          asset_content_type: application/zip

